### ISSUE TITLE
How do both Heroku apps work together?

### ISSUE THREAD

**Issue by IHIutch** [SHxKM/django-vue-ssr#15]
Just want to make sure I understand your setup correctly. Do you have separate frontend and backend apps in heroku?

**Comment by IHIutch** [comment]
Nevermind, I misunderstood what you meant [here](https://github.com/SHxKM/django-vue-ssr/issues/3#issue-427451695).

I guess my question becomes, how do you wake up both apps? Or does that happen automatically when the FE requests data from the BE?

**Comment by SHxKM** [comment]
Hi @IHIutch - yes, the frontend will trigger an API call to the backend, which will wake that app as well. Please note this is an “old” project by now.

**Comment by IHIutch** [comment]
Thanks for the update, and no worries about it being old. Im working on a project that will be similar and am doing a bit of research. Thanks for the work and the quick reply!
