### ISSUE TITLE
Find a way to run this in one Heroku app

### ISSUE THREAD

**Issue by SHxKM** [SHxKM/django-vue-ssr#3]
Despite a lot of research and effort, I couldn't find a way to ship both the backend and frontend apps to one Heroku application, mainly due to the fact that it's impossible/super-hard to proxy between them (frontend needs to proxy its `/api` to backend).

**Comment by SHxKM** [comment]
The more I think about it, the less inclined I am to do this. The "challenge" and possibly educational gains from this kind of change don't seem to be worth it. Maybe a Docker edition would be better?

**Comment by michaelycus** [comment]
I just lost so many days trying to deploy an Django + Nuxt.js application in one single Heroku App and now I read your comment.
Thanks bro!
You just save me from more days of suffering and pain.
